import { Chassis, Addon, Order, GlobalSettings } from './types';

export const INITIAL_CHASSIS: Chassis[] = [
  {
    id: 'chassis-1',
    title: 'SOHUB V-45 Premium Heavy Duty',
    type: 'imported',
    base_price: 380000,
    chiller_support: true,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    specifications: {
      slots: 60,
      capacity: '450 Snacks & Drinks',
      dimensions: '1940 x 1030 x 790 mm',
      temperature_range: '4°C - 25°C',
      power_consumption: '350W Cooling / 40W Standby',
    },
  },
  {
    id: 'chassis-2',
    title: 'SOHUB V-32 Slim Compact',
    type: 'imported',
    base_price: 260000,
    chiller_support: false,
    is_active: true,
    created_at: '2026-01-15T11:30:00Z',
    specifications: {
      slots: 32,
      capacity: '240 Items',
      dimensions: '1830 x 780 x 700 mm',
      temperature_range: 'Ambient Room Temp',
      power_consumption: '45W Standby',
    },
  },
  {
    id: 'chassis-3',
    title: 'SOHUB Local Build Eco 50',
    type: 'local',
    base_price: 195000,
    chiller_support: true,
    is_active: true,
    created_at: '2026-02-01T09:15:00Z',
    specifications: {
      slots: 50,
      capacity: '380 Items',
      dimensions: '1900 x 950 x 750 mm',
      temperature_range: '6°C - 22°C',
      power_consumption: '280W Cooling',
    },
  },
  {
    id: 'chassis-4',
    title: 'SOHUB Frozen & Ice Cream Vender',
    type: 'imported',
    base_price: 490000,
    chiller_support: true,
    is_active: true,
    created_at: '2026-02-12T14:20:00Z',
    specifications: {
      slots: 40,
      capacity: '300 Frozen Packs',
      dimensions: '1980 x 1100 x 850 mm',
      temperature_range: '-18°C - -22°C',
      power_consumption: '650W Deep Freeze',
    },
  },
  {
    id: 'chassis-5',
    title: 'SOHUB Mini Wall Mount Lockers',
    type: 'local',
    base_price: 135000,
    chiller_support: false,
    is_active: false,
    created_at: '2026-03-05T08:45:00Z',
    specifications: {
      slots: 18,
      capacity: '18 Custom Parcels',
      dimensions: '1200 x 600 x 400 mm',
      temperature_range: 'Ambient',
      power_consumption: '20W Standby',
    },
  },
];

export const INITIAL_ADDONS: Addon[] = [
  {
    id: 'addon-1',
    name: '21.5" Full HD Capacitive Touchscreen UI',
    description: 'High-brightness industrial touch screen for interactive product selection and video ads.',
    category: 'hardware',
    price: 45000,
    is_tbd: false,
    sort_order: 1,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-2',
    name: 'Unified bKash / Nagad QR Payment Gateway & POS',
    description: 'Direct API integration with mobile financial services and bank card reader.',
    category: 'payment',
    price: 35000,
    is_tbd: false,
    sort_order: 2,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-3',
    name: 'IoT Telemetry & Cloud Inventory Controller',
    description: 'Real-time stock monitoring, sales telemetry, and remote price modification portal.',
    category: 'software',
    price: 25000,
    is_tbd: false,
    sort_order: 3,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-4',
    name: 'Full Body 3M Vinyl Custom Brand Wrapping',
    description: 'High resolution UV printed vinyl wrap tailored to client logo & brand design.',
    category: 'branding',
    price: 0,
    is_tbd: true, // Needs admin estimation based on artwork complexity
    sort_order: 4,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-5',
    name: 'R134a Industrial Heavy Cooling Unit',
    description: 'Upgraded compressor unit for high humidity & hot outdoor ambient conditions.',
    category: 'hardware',
    price: 55000,
    is_tbd: false,
    sort_order: 5,
    is_active: true,
    compatible_models: ['SOHUB V-45 Premium Heavy Duty', 'SOHUB Local Build Eco 50'],
  },
  {
    id: 'addon-6',
    name: 'Soft-Drop Conveyor Elevator System',
    description: 'Protects fragile items (glass bottles, electronic items) during dispensing.',
    category: 'hardware',
    price: 0,
    is_tbd: true,
    sort_order: 6,
    is_active: true,
    compatible_models: ['SOHUB V-45 Premium Heavy Duty', 'SOHUB Frozen & Ice Cream Vender'],
  },
  {
    id: 'addon-7',
    name: 'Multi-Currency Bill Acceptor & Coin Recycler',
    description: 'Cash payment module supporting BDT 10, 20, 50, 100, 500 notes.',
    category: 'payment',
    price: 28000,
    is_tbd: false,
    sort_order: 7,
    is_active: true,
    compatible_models: ['All'],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'SHB-2026-0891',
    customer_name: 'Tanvir Ahmed',
    customer_email: 'tanvir.ahmed@grameenphone.com',
    customer_phone: '+880 1711-908234',
    customer_company: 'Grameenphone Innovation Hub',
    delivery_location: 'GP House, Bashundhara R/A, Dhaka-1229',
    chassis_id: 'chassis-1',
    chassis_title: 'SOHUB V-45 Premium Heavy Duty',
    chassis_base_price: 380000,
    selected_addons: [
      {
        addon_id: 'addon-1',
        addon_name: '21.5" Full HD Capacitive Touchscreen UI',
        original_price: 45000,
        is_tbd: false,
        final_price: 45000,
      },
      {
        addon_id: 'addon-2',
        addon_name: 'Unified bKash / Nagad QR Payment Gateway & POS',
        original_price: 35000,
        is_tbd: false,
        final_price: 35000,
      },
      {
        addon_id: 'addon-4',
        addon_name: 'Full Body 3M Vinyl Custom Brand Wrapping',
        original_price: 0,
        is_tbd: true,
        final_price: 18500, // Admin estimated
      },
    ],
    subtotal: 478500,
    vat_rate: 5,
    vat_amount: 23925,
    monthly_recurring_fee: 5000,
    grand_total: 502425,
    status: 'Confirmed',
    created_at: '2026-07-21T14:30:00Z',
    updated_at: '2026-07-22T09:15:00Z',
    admin_notes: 'Client requested rush delivery for GP House HQ opening.',
  },
  {
    id: 'ord-1002',
    order_number: 'SHB-2026-0892',
    customer_name: 'Nadia Rahman',
    customer_email: 'nadia.r@unilever.com.bd',
    customer_phone: '+880 1844-551122',
    customer_company: 'Unilever Bangladesh Ltd.',
    delivery_location: 'ZN Tower, Plot 2, Road 8, Gulshan-1, Dhaka',
    chassis_id: 'chassis-4',
    chassis_title: 'SOHUB Frozen & Ice Cream Vender',
    chassis_base_price: 490000,
    selected_addons: [
      {
        addon_id: 'addon-1',
        addon_name: '21.5" Full HD Capacitive Touchscreen UI',
        original_price: 45000,
        is_tbd: false,
        final_price: 45000,
      },
      {
        addon_id: 'addon-3',
        addon_name: 'IoT Telemetry & Cloud Inventory Controller',
        original_price: 25000,
        is_tbd: false,
        final_price: 25000,
      },
      {
        addon_id: 'addon-6',
        addon_name: 'Soft-Drop Conveyor Elevator System',
        original_price: 0,
        is_tbd: true,
        final_price: 32000, // Needs re-estimation by admin
      },
    ],
    subtotal: 592000,
    vat_rate: 5,
    vat_amount: 29600,
    monthly_recurring_fee: 7500,
    grand_total: 621600,
    status: 'Pending',
    created_at: '2026-07-22T10:15:00Z',
    updated_at: '2026-07-22T10:15:00Z',
    admin_notes: 'Requires custom temperature calibration for Walls Ice Cream tubs.',
  },
  {
    id: 'ord-1003',
    order_number: 'SHB-2026-0893',
    customer_name: 'Kazi Mahbub',
    customer_email: 'kazi@pathao.com',
    customer_phone: '+880 1912-334455',
    customer_company: 'Pathao Technologies',
    delivery_location: 'Pathao Tower, Road 11, Banani, Dhaka',
    chassis_id: 'chassis-3',
    chassis_title: 'SOHUB Local Build Eco 50',
    chassis_base_price: 195000,
    selected_addons: [
      {
        addon_id: 'addon-2',
        addon_name: 'Unified bKash / Nagad QR Payment Gateway & POS',
        original_price: 35000,
        is_tbd: false,
        final_price: 35000,
      },
      {
        addon_id: 'addon-4',
        addon_name: 'Full Body 3M Vinyl Custom Brand Wrapping',
        original_price: 0,
        is_tbd: true,
        final_price: 15000,
      },
    ],
    subtotal: 245000,
    vat_rate: 0,
    vat_amount: 0,
    monthly_recurring_fee: 5000,
    grand_total: 245000,
    status: 'Quotation Sent',
    created_at: '2026-07-22T16:45:00Z',
    updated_at: '2026-07-23T08:20:00Z',
    admin_notes: 'Quotation sent via email. Awaiting CEO signoff.',
  },
  {
    id: 'ord-1004',
    order_number: 'SHB-2026-0894',
    customer_name: 'Dr. Sharmin Akter',
    customer_email: 'sharmin@squarepharma.com',
    customer_phone: '+880 1730-889900',
    customer_company: 'Square Pharmaceuticals Ltd.',
    delivery_location: 'Square Centre, 48 Mohakhali C/A, Dhaka',
    chassis_id: 'chassis-1',
    chassis_title: 'SOHUB V-45 Premium Heavy Duty',
    chassis_base_price: 380000,
    selected_addons: [
      {
        addon_id: 'addon-1',
        addon_name: '21.5" Full HD Capacitive Touchscreen UI',
        original_price: 45000,
        is_tbd: false,
        final_price: 45000,
      },
      {
        addon_id: 'addon-5',
        addon_name: 'R134a Industrial Heavy Cooling Unit',
        original_price: 55000,
        is_tbd: false,
        final_price: 55000,
      },
      {
        addon_id: 'addon-7',
        addon_name: 'Multi-Currency Bill Acceptor & Coin Recycler',
        original_price: 28000,
        is_tbd: false,
        final_price: 28000,
      },
    ],
    subtotal: 508000,
    vat_rate: 5,
    vat_amount: 25400,
    monthly_recurring_fee: 5000,
    grand_total: 533400,
    status: 'Pending',
    created_at: '2026-07-23T09:10:00Z',
    updated_at: '2026-07-23T09:10:00Z',
    admin_notes: 'Medicine vending configuration requested with temperature logger.',
  },
  {
    id: 'ord-1005',
    order_number: 'SHB-2026-0895',
    customer_name: 'Rafiqul Islam',
    customer_email: 'rafiq@nagad.com.bd',
    customer_phone: '+880 1819-001122',
    customer_company: 'Nagad Digital Bank',
    delivery_location: 'Nagad HQ, Kemal Ataturk Avenue, Banani',
    chassis_id: 'chassis-2',
    chassis_title: 'SOHUB V-32 Slim Compact',
    chassis_base_price: 260000,
    selected_addons: [
      {
        addon_id: 'addon-3',
        addon_name: 'IoT Telemetry & Cloud Inventory Controller',
        original_price: 25000,
        is_tbd: false,
        final_price: 25000,
      },
    ],
    subtotal: 285000,
    vat_rate: 5,
    vat_amount: 14250,
    monthly_recurring_fee: 5000,
    grand_total: 299250,
    status: 'Cancelled',
    created_at: '2026-07-18T11:00:00Z',
    updated_at: '2026-07-19T14:00:00Z',
    admin_notes: 'Cancelled due to budget reallocation.',
  },
];

export const INITIAL_SETTINGS: GlobalSettings = {
  default_vat_rate: 5,
  default_monthly_fee: 5000,
  default_payment_terms: '60% Advance Work Order, 40% Delivery & Commissioning',
  bank_details: {
    bank_name: 'Eastern Bank PLC (EBL)',
    account_name: 'SOHUB AUTOMATION & TECH LTD',
    account_number: '1041070284912',
    branch: 'Gulshan Corporate Branch, Dhaka',
    routing_number: '090261748',
  },
  terms_and_conditions: [
    'Quotation validity is 30 days from issuance date.',
    'Delivery lead time is 15-20 working days post 60% advance payment.',
    'Warranty covers 1 Year free parts & remote telemetry service.',
    'Monthly IoT cloud subscription (BDT 5,000/mo) is billed quarterly in advance.',
    'Site preparation, 220V grounded power socket & WiFi/4G connection to be provided by client.',
    'Custom vinyl artwork must be provided in vector AI/PDF format.',
    'Prices are exclusive of transport outside Dhaka metropolitan area unless specified.',
    'SOHUB reserves ownership of hardware until final payment clearance.',
  ],
};
