import { Chassis, Addon, Order, GlobalSettings } from './types';

export const INITIAL_CHASSIS: Chassis[] = [
  {
    id: 'chassis-1',
    title: 'SOHUB V-45 Premium Heavy Duty',
    type: 'imported',
    base_price: 380000,
    short_description: 'Premium imported heavy duty chassis with dual tempered glass & telemetry integration.',
    image_url: 'https://machines.sohub.com.bd/assets/vending-v45.png',
    chiller_support: true,
    is_active: true,
    created_at: '2026-01-10T10:00:00Z',
    specifications: {
      slots: 60,
      capacity: '450 Snacks & Drinks',
      dimensions: '1940 x 1030 x 790 mm',
      temperature_range: '4°C - 25°C',
      power_consumption: '350W Cooling / 40W Standby',
      display_type: '21.5" HD Touchscreen',
    },
  },
  {
    id: 'chassis-2',
    title: 'SOHUB V-32 Slim Compact',
    type: 'imported',
    base_price: 260000,
    short_description: 'Compact slim vending machine chassis ideal for office corridors & small spaces.',
    image_url: 'https://machines.sohub.com.bd/assets/vending-v32.png',
    chiller_support: false,
    is_active: true,
    created_at: '2026-01-15T11:30:00Z',
    specifications: {
      slots: 32,
      capacity: '240 Items',
      dimensions: '1830 x 780 x 700 mm',
      temperature_range: 'Ambient Room Temp',
      power_consumption: '45W Standby',
      display_type: '10.1" Touch Display',
    },
  },
  {
    id: 'chassis-3',
    title: 'SOHUB Local Build Eco 50',
    type: 'local',
    base_price: 195000,
    short_description: 'Locally assembled affordable chassis with powder-coated steel & SOHUB controller.',
    image_url: 'https://machines.sohub.com.bd/assets/vending-eco50.png',
    chiller_support: true,
    is_active: true,
    created_at: '2026-02-01T09:15:00Z',
    specifications: {
      slots: 50,
      capacity: '380 Items',
      dimensions: '1900 x 950 x 750 mm',
      temperature_range: '6°C - 22°C',
      power_consumption: '280W Cooling',
      display_type: 'Keypad + LCD Display',
    },
  },
];

export const INITIAL_ADDONS: Addon[] = [
  {
    id: 'addon-1',
    name: 'Built-in Chiller Unit',
    description: 'Refrigeration module for cold beverages, chocolates, and dairy products (4°C - 25°C).',
    category: 'hardware',
    price: 40000,
    is_tbd: false,
    sort_order: 1,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-2',
    name: 'Touchscreen Display Upgrade',
    description: '10-inch interactive HD touchscreen display for product selection & advertisements.',
    category: 'hardware',
    price: 18000,
    is_tbd: false,
    sort_order: 2,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-3',
    name: 'POS Payment Module (EBL POS)',
    description: 'Credit/Debit Card POS payment integration hardware module.',
    category: 'payment',
    price: 10000,
    is_tbd: false,
    sort_order: 3,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-4',
    name: 'Custom Branding Wrap',
    description: 'Full machine high-quality vinyl wrap with custom company branding and design.',
    category: 'branding',
    price: 12000,
    is_tbd: false,
    sort_order: 4,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-5',
    name: 'Cash Acceptor & Bill Validator',
    description: 'Paper currency cash acceptor module for cash payments.',
    category: 'hardware',
    price: 15000,
    is_tbd: false,
    sort_order: 5,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-6',
    name: 'Stabilizer & Surge Protector',
    description: 'Voltage stabilizer & power surge protection for BD grid conditions.',
    category: 'hardware',
    price: 8000,
    is_tbd: false,
    sort_order: 6,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-7',
    name: 'Cashless Payment Gateway Integration',
    description: 'bKash, Nagad, SSLCommerz, NFC Card, & Student/Employee ID Card payment integration.',
    category: 'payment',
    price: 0,
    is_tbd: true,
    sort_order: 7,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-8',
    name: 'Custom UI / Android App Customization',
    description: 'Custom branded UI menu and promotional banner carousel for machine touchscreen.',
    category: 'software',
    price: 0,
    is_tbd: true,
    sort_order: 8,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-9',
    name: 'Inventory & Refill Management Service',
    description: 'SOHUB managed product refilling, stock monitoring, and local maintenance service.',
    category: 'software',
    price: 0,
    is_tbd: true,
    sort_order: 9,
    is_active: true,
    compatible_models: ['All'],
  },
  {
    id: 'addon-10',
    name: 'SOHUB Cloud Backend Platform',
    description: 'Real-time sales dashboard, inventory refill alerts, remote restart/lock, & error logs.',
    category: 'software',
    price: 5000,
    is_tbd: false,
    sort_order: 10,
    is_active: true,
    compatible_models: ['All'],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'SHB-2026-0891',
    customer_name: 'Tanvir Ahmed',
    customer_email: 'tanvir.ahmed@grameenphone.com',
    customer_phone: '+880 1711-908234',
    customer_company: 'Grameenphone Innovation Hub',
    delivery_location: 'GP House, Bashundhara R/A, Dhaka-1229',
    chassis_id: 'chassis-1',
    chassis_title: 'SOHUB V-45 Premium Heavy Duty',
    chassis_base_price: 380000,
    selected_addons: [
      {
        addon_id: 'addon-1',
        addon_name: 'Built-in Chiller Unit',
        original_price: 40000,
        is_tbd: false,
        final_price: 40000,
      },
      {
        addon_id: 'addon-3',
        addon_name: 'POS Payment Module (EBL POS)',
        original_price: 10000,
        is_tbd: false,
        final_price: 10000,
      },
      {
        addon_id: 'addon-4',
        addon_name: 'Custom Branding Wrap',
        original_price: 12000,
        is_tbd: false,
        final_price: 12000,
      },
    ],
    subtotal: 442000,
    vat_rate: 5,
    vat_amount: 22100,
    monthly_recurring_fee: 5000,
    grand_total: 464100,
    status: 'Confirmed',
    created_at: '2026-07-21T14:30:00Z',
    updated_at: '2026-07-22T09:15:00Z',
    admin_notes: 'Client requested rush delivery for GP House HQ opening.',
  },
];

export const INITIAL_SETTINGS: GlobalSettings = {
  default_vat_rate: 5,
  default_monthly_fee: 5000,
  default_payment_terms: '60% Advance Work Order, 40% Delivery & Commissioning',
  bank_details: {
    bank_name: 'Eastern Bank PLC (EBL)',
    account_name: 'SOHUB AUTOMATION & TECH LTD',
    account_number: '1041070284912',
    branch: 'Gulshan Corporate Branch, Dhaka',
    routing_number: '090261748',
  },
  terms_and_conditions: [
    'Quotation validity is 30 days from issuance date.',
    'Delivery lead time is 15-20 working days post 60% advance payment.',
    'Warranty covers 1 Year free parts & remote telemetry service.',
    'Monthly IoT cloud subscription (BDT 5,000/mo) is billed quarterly in advance.',
    'Site preparation, 220V grounded power socket & WiFi/4G connection to be provided by client.',
    'Custom vinyl artwork must be provided in vector AI/PDF format.',
    'Prices are exclusive of transport outside Dhaka metropolitan area unless specified.',
    'SOHUB reserves ownership of hardware until final payment clearance.',
  ],
};
